### ISSUE TITLE
Added preprocessor-check on exist support SSE

### ISSUE THREAD

**Issue by galek** [SergeyMakeev/TaskScheduler#1]
ENG:
Added check on exist support SSE on compiler, if not exist, will use equal C-code.(Is needed for porting on Android
[patch.zip](https://github.com/SergeyMakeev/TaskScheduler/files/194610/patch.zip)

RU:
Добавлена проверка на наличие SSE, если поддержки нету, используется C код.

**Comment by galek** [comment]
Edit: Detected, what macro **SSE** unvalible under VS :(

Corrected versions:
https://gist.github.com/galek/9a0fb8081efb68949c8a87a808351198
https://gist.github.com/galek/a255a030774396bc4b2683acd6180ff1

**Comment by SergeyMakeev** [comment]
Hi Galek,

Thank you for your changes
You sent a patch for old version of scheduler, so I apply your changes to latest version and commit this changes.
